In [9]:
from numpy import dot, array

In [11]:
# produit matriciel
matrix1 = array([[1, 6], [5, 7], [0, 2]])
matrix2 = array([[2, 1, 0], [1, 9, 5]])
produit = dot(matrix1, matrix2)
produit2 = dot(matrix2, matrix1)
print(produit)
print(produit2)

[[ 8 55 30]
 [17 68 35]
 [ 2 18 10]]
[[ 7 19]
 [46 79]]
